import datetime as _dt

SCHEDULE_2025 = [
        # Week 1
        {'week': 1, 'date': _dt.date(2025, 9, 4),  'time': '8:20 pm', 'away': 'Dallas Cowboys',      'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 5),  'time': '8:00 pm', 'away': 'Kansas City Chiefs',   'home': 'Los Angeles Chargers', 'note': 'Brazil'},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'New Orleans Saints', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Cincinnati Bengals',   'home': 'Cleveland Browns', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Las Vegas Raiders',    'home': 'New England Patriots', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'Indianapolis Colts', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Washington Commanders', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Pittsburgh Steelers',  'home': 'New York Jets', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '1:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Atlanta Falcons', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '4:05 pm', 'away': 'San Francisco 49ers',  'home': 'Seattle Seahawks', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '4:05 pm', 'away': 'Tennessee Titans',     'home': 'Denver Broncos', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '4:25 pm', 'away': 'Detroit Lions',        'home': 'Green Bay Packers', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '4:25 pm', 'away': 'Houston Texans',       'home': 'Los Angeles Rams', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 7),  'time': '8:20 pm', 'away': 'Baltimore Ravens',     'home': 'Buffalo Bills', 'note': ''},
        {'week': 1, 'date': _dt.date(2025, 9, 8),  'time': '8:15 pm', 'away': 'Minnesota Vikings',     'home': 'Chicago Bears', 'note': ''},

        # Week 2
        {'week': 2, 'date': _dt.date(2025, 9, 11), 'time': '8:15 pm', 'away': 'Washington Commanders','home': 'Green Bay Packers', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Buffalo Bills',        'home': 'New York Jets', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Chicago Bears',        'home': 'Detroit Lions', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'Baltimore Ravens', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Jacksonville Jaguars', 'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Los Angeles Rams',     'home': 'Tennessee Titans', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'Miami Dolphins', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Dallas Cowboys', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'San Francisco 49ers',  'home': 'New Orleans Saints', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '4:05 pm', 'away': 'Carolina Panthers',    'home': 'Arizona Cardinals', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '4:05 pm', 'away': 'Denver Broncos',       'home': 'Indianapolis Colts', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '4:25 pm', 'away': 'Philadelphia Eagles',  'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 14), 'time': '8:20 pm', 'away': 'Atlanta Falcons',      'home': 'Minnesota Vikings', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 15), 'time': '7:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Houston Texans', 'note': ''},
        {'week': 2, 'date': _dt.date(2025, 9, 15), 'time': '10:00 pm','away': 'Los Angeles Chargers', 'home': 'Las Vegas Raiders', 'note': ''},

        # Week 3
        {'week': 3, 'date': _dt.date(2025, 9, 18), 'time': '8:15 pm', 'away': 'Miami Dolphins',       'home': 'Buffalo Bills', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Atlanta Falcons',      'home': 'Carolina Panthers', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Cincinnati Bengals',   'home': 'Minnesota Vikings', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Green Bay Packers',    'home': 'Cleveland Browns', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Houston Texans',       'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Indianapolis Colts',   'home': 'Tennessee Titans', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Las Vegas Raiders',    'home': 'Washington Commanders', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Los Angeles Rams',     'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'New York Jets',        'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '1:00 pm', 'away': 'Pittsburgh Steelers',  'home': 'New England Patriots', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '4:05 pm', 'away': 'Denver Broncos',       'home': 'Los Angeles Chargers', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '4:05 pm', 'away': 'New Orleans Saints',   'home': 'Seattle Seahawks', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '4:25 pm', 'away': 'Arizona Cardinals',    'home': 'San Francisco 49ers', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '4:25 pm', 'away': 'Dallas Cowboys',       'home': 'Chicago Bears', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 21), 'time': '8:20 pm', 'away': 'Kansas City Chiefs',   'home': 'New York Giants', 'note': ''},
        {'week': 3, 'date': _dt.date(2025, 9, 22), 'time': '8:15 pm', 'away': 'Detroit Lions',        'home': 'Baltimore Ravens', 'note': ''},

        # Week 4
        {'week': 4, 'date': _dt.date(2025, 9, 25), 'time': '8:15 pm', 'away': 'Seattle Seahawks',     'home': 'Arizona Cardinals', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '9:30 am', 'away': 'Minnesota Vikings',    'home': 'Pittsburgh Steelers', 'note': 'Dublin'},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'New England Patriots', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'Detroit Lions', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'New York Giants', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Buffalo Bills', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Philadelphia Eagles',  'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Tennessee Titans',     'home': 'Houston Texans', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '1:00 pm', 'away': 'Washington Commanders','home': 'Atlanta Falcons', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '4:05 pm', 'away': 'Indianapolis Colts',   'home': 'Los Angeles Rams', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '4:05 pm', 'away': 'Jacksonville Jaguars', 'home': 'San Francisco 49ers', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '4:25 pm', 'away': 'Baltimore Ravens',     'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '4:25 pm', 'away': 'Chicago Bears',        'home': 'Las Vegas Raiders', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 28), 'time': '8:20 pm', 'away': 'Green Bay Packers',    'home': 'Dallas Cowboys', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 29), 'time': '7:15 pm', 'away': 'New York Jets',        'home': 'Miami Dolphins', 'note': ''},
        {'week': 4, 'date': _dt.date(2025, 9, 29), 'time': '8:15 pm', 'away': 'Cincinnati Bengals',   'home': 'Denver Broncos', 'note': ''},

        # Week 5
        {'week': 5, 'date': _dt.date(2025, 10, 2), 'time': '8:15 pm', 'away': 'San Francisco 49ers',  'home': 'Los Angeles Rams', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '9:30 am', 'away': 'Minnesota Vikings',    'home': 'Cleveland Browns', 'note': 'London'},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'Dallas Cowboys',       'home': 'New York Jets', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'Denver Broncos',       'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'Houston Texans',       'home': 'Baltimore Ravens', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'Las Vegas Raiders',    'home': 'Indianapolis Colts', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'Carolina Panthers', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '1:00 pm', 'away': 'New York Giants',      'home': 'New Orleans Saints', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '4:05 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Seattle Seahawks', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '4:05 pm', 'away': 'Tennessee Titans',     'home': 'Arizona Cardinals', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '4:25 pm', 'away': 'Detroit Lions',        'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '4:25 pm', 'away': 'Washington Commanders','home': 'Los Angeles Chargers', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 5), 'time': '8:20 pm', 'away': 'New England Patriots', 'home': 'Buffalo Bills', 'note': ''},
        {'week': 5, 'date': _dt.date(2025, 10, 6), 'time': '8:15 pm', 'away': 'Kansas City Chiefs',   'home': 'Jacksonville Jaguars', 'note': ''},

        # Week 6
        {'week': 6, 'date': _dt.date(2025, 10, 9), 'time': '8:15 pm', 'away': 'Philadelphia Eagles',  'home': 'New York Giants', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '9:30 am', 'away': 'Denver Broncos',      'home': 'New York Jets', 'note': 'London'},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'Indianapolis Colts', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Dallas Cowboys',       'home': 'Carolina Panthers', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Los Angeles Chargers','home': 'Miami Dolphins', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Los Angeles Rams',     'home': 'Baltimore Ravens', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'San Francisco 49ers',  'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '4:05 pm', 'away': 'Tennessee Titans',     'home': 'Las Vegas Raiders', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '4:25 pm', 'away': 'Cincinnati Bengals',   'home': 'Green Bay Packers', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '4:25 pm', 'away': 'New England Patriots', 'home': 'New Orleans Saints', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 12), 'time': '8:20 pm', 'away': 'Detroit Lions',        'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 13), 'time': '7:15 pm', 'away': 'Buffalo Bills',        'home': 'Atlanta Falcons', 'note': ''},
        {'week': 6, 'date': _dt.date(2025, 10, 13), 'time': '8:15 pm', 'away': 'Chicago Bears',        'home': 'Washington Commanders', 'note': ''},

        # Week 7
        {'week': 7, 'date': _dt.date(2025, 10, 16), 'time': '8:15 pm', 'away': 'Pittsburgh Steelers', 'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '9:30 am', 'away': 'Los Angeles Rams',     'home': 'Jacksonville Jaguars', 'note': 'London'},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'New York Jets', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'Las Vegas Raiders',    'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'Cleveland Browns', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'Tennessee Titans', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'New Orleans Saints',    'home': 'Chicago Bears', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '1:00 pm', 'away': 'Philadelphia Eagles',  'home': 'Minnesota Vikings', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '4:05 pm', 'away': 'Indianapolis Colts',   'home': 'Los Angeles Chargers', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '4:05 pm', 'away': 'New York Giants',      'home': 'Denver Broncos', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '4:25 pm', 'away': 'Green Bay Packers',    'home': 'Arizona Cardinals', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '4:25 pm', 'away': 'Washington Commanders','home': 'Dallas Cowboys', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 19), 'time': '8:20 pm', 'away': 'Atlanta Falcons',      'home': 'San Francisco 49ers', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 20), 'time': '7:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Detroit Lions', 'note': ''},
        {'week': 7, 'date': _dt.date(2025, 10, 20), 'time': '10:00 pm','away': 'Houston Texans',       'home': 'Seattle Seahawks', 'note': ''},

        # Week 8
        {'week': 8, 'date': _dt.date(2025, 10, 23), 'time': '8:15 pm', 'away': 'Minnesota Vikings',    'home': 'Los Angeles Chargers', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'Buffalo Bills',        'home': 'Carolina Panthers', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'Chicago Bears',        'home': 'Baltimore Ravens', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'New England Patriots', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'Atlanta Falcons', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'New York Jets',        'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '1:00 pm', 'away': 'San Francisco 49ers',  'home': 'Houston Texans', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '4:05 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'New Orleans Saints', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '4:25 pm', 'away': 'Dallas Cowboys',       'home': 'Denver Broncos', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '4:25 pm', 'away': 'Tennessee Titans',     'home': 'Indianapolis Colts', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 26), 'time': '8:20 pm', 'away': 'Green Bay Packers',    'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 8, 'date': _dt.date(2025, 10, 27), 'time': '8:15 pm', 'away': 'Washington Commanders','home': 'Kansas City Chiefs', 'note': ''},

        # Week 9
        {'week': 9, 'date': _dt.date(2025, 10, 30), 'time': '8:15 pm', 'away': 'Baltimore Ravens',     'home': 'Miami Dolphins', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Atlanta Falcons',      'home': 'New England Patriots', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'Green Bay Packers', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Chicago Bears',        'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Denver Broncos',       'home': 'Houston Texans', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Indianapolis Colts',   'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'Tennessee Titans', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'Minnesota Vikings',    'home': 'Detroit Lions', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '1:00 pm', 'away': 'San Francisco 49ers',  'home': 'New York Giants', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '4:05 pm', 'away': 'Jacksonville Jaguars', 'home': 'Las Vegas Raiders', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '4:05 pm', 'away': 'New Orleans Saints',   'home': 'Los Angeles Rams', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '4:25 pm', 'away': 'Kansas City Chiefs',   'home': 'Buffalo Bills', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 2),  'time': '8:20 pm', 'away': 'Seattle Seahawks',     'home': 'Washington Commanders', 'note': ''},
        {'week': 9, 'date': _dt.date(2025, 11, 3),  'time': '8:15 pm', 'away': 'Arizona Cardinals',    'home': 'Dallas Cowboys', 'note': ''},

        # Week 10
        {'week': 10,'date': _dt.date(2025, 11, 6),  'time': '8:15 pm', 'away': 'Las Vegas Raiders',    'home': 'Denver Broncos', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '9:30 am', 'away': 'Atlanta Falcons',      'home': 'Indianapolis Colts', 'note': 'Berlin'},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'Baltimore Ravens',     'home': 'Minnesota Vikings', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'Buffalo Bills',        'home': 'Miami Dolphins', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'New York Jets', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'Jacksonville Jaguars', 'home': 'Houston Texans', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Carolina Panthers', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Chicago Bears', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '4:05 pm', 'away': 'Arizona Cardinals',    'home': 'Seattle Seahawks', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '4:25 pm', 'away': 'Detroit Lions',        'home': 'Washington Commanders', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '4:25 pm', 'away': 'Los Angeles Rams',     'home': 'San Francisco 49ers', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 9),  'time': '8:20 pm', 'away': 'Pittsburgh Steelers',  'home': 'Los Angeles Chargers', 'note': ''},
        {'week': 10,'date': _dt.date(2025, 11, 10), 'time': '8:15 pm', 'away': 'Philadelphia Eagles',  'home': 'Green Bay Packers', 'note': ''},

        # Week 11
        {'week': 11,'date': _dt.date(2025, 11, 13), 'time': '8:15 pm', 'away': 'New York Jets',        'home': 'New England Patriots', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '9:30 am', 'away': 'Washington Commanders','home': 'Miami Dolphins', 'note': 'London'},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'Atlanta Falcons', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Chicago Bears',        'home': 'Minnesota Vikings', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Cincinnati Bengals',   'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Green Bay Packers',    'home': 'New York Giants', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Houston Texans',       'home': 'Tennessee Titans', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '1:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Buffalo Bills', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '4:05 pm', 'away': 'San Francisco 49ers',  'home': 'Arizona Cardinals', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '4:05 pm', 'away': 'Seattle Seahawks',     'home': 'Los Angeles Rams', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '4:25 pm', 'away': 'Baltimore Ravens',     'home': 'Cleveland Browns', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '4:25 pm', 'away': 'Kansas City Chiefs',   'home': 'Denver Broncos', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 16), 'time': '8:20 pm', 'away': 'Detroit Lions',        'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 11,'date': _dt.date(2025, 11, 17), 'time': '8:15 pm', 'away': 'Dallas Cowboys',       'home': 'Las Vegas Raiders', 'note': ''},

        # Week 12
        {'week': 12,'date': _dt.date(2025, 11, 20), 'time': '8:15 pm', 'away': 'Buffalo Bills',        'home': 'Houston Texans', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'Indianapolis Colts',   'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'Minnesota Vikings',    'home': 'Green Bay Packers', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Detroit Lions', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'New York Jets',        'home': 'Baltimore Ravens', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'Pittsburgh Steelers',  'home': 'Chicago Bears', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'Tennessee Titans', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '4:05 pm', 'away': 'Cleveland Browns',     'home': 'Las Vegas Raiders', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '4:05 pm', 'away': 'Jacksonville Jaguars', 'home': 'Arizona Cardinals', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '4:25 pm', 'away': 'Atlanta Falcons',      'home': 'New Orleans Saints', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '4:25 pm', 'away': 'Philadelphia Eagles',  'home': 'Dallas Cowboys', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 23), 'time': '8:20 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Los Angeles Rams', 'note': ''},
        {'week': 12,'date': _dt.date(2025, 11, 24), 'time': '8:15 pm', 'away': 'Carolina Panthers',    'home': 'San Francisco 49ers', 'note': ''},

        # Week 13
        {'week': 13,'date': _dt.date(2025, 11, 27), 'time': '1:00 pm', 'away': 'Green Bay Packers',    'home': 'Detroit Lions', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 27), 'time': '4:30 pm', 'away': 'Kansas City Chiefs',   'home': 'Dallas Cowboys', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 27), 'time': '8:20 pm', 'away': 'Cincinnati Bengals',   'home': 'Baltimore Ravens', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 28), 'time': '3:00 pm', 'away': 'Chicago Bears',        'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'Atlanta Falcons',      'home': 'New York Jets', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'Houston Texans',       'home': 'Indianapolis Colts', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'Jacksonville Jaguars', 'home': 'Tennessee Titans', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'Los Angeles Rams',     'home': 'Carolina Panthers', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Miami Dolphins', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '1:00 pm', 'away': 'San Francisco 49ers',  'home': 'Cleveland Browns', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '4:05 pm', 'away': 'Minnesota Vikings',    'home': 'Seattle Seahawks', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '4:25 pm', 'away': 'Buffalo Bills',        'home': 'Pittsburgh Steelers', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '4:25 pm', 'away': 'Las Vegas Raiders',    'home': 'Los Angeles Chargers', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 11, 30), 'time': '8:20 pm', 'away': 'Denver Broncos',       'home': 'Washington Commanders', 'note': ''},
        {'week': 13,'date': _dt.date(2025, 12, 1),  'time': '8:15 pm', 'away': 'New York Giants',      'home': 'New England Patriots', 'note': ''},

        # Week 14
        {'week': 14,'date': _dt.date(2025, 12, 4),  'time': '8:15 pm', 'away': 'Dallas Cowboys',       'home': 'Detroit Lions', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Chicago Bears',        'home': 'Green Bay Packers', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Indianapolis Colts',   'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'New York Jets', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Pittsburgh Steelers',  'home': 'Baltimore Ravens', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'Atlanta Falcons', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Tennessee Titans',     'home': 'Cleveland Browns', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '1:00 pm', 'away': 'Washington Commanders','home': 'Minnesota Vikings', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '4:05 pm', 'away': 'Denver Broncos',       'home': 'Las Vegas Raiders', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '4:25 pm', 'away': 'Cincinnati Bengals',   'home': 'Buffalo Bills', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '4:25 pm', 'away': 'Los Angeles Rams',     'home': 'Arizona Cardinals', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 7),  'time': '8:20 pm', 'away': 'Houston Texans',       'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 14,'date': _dt.date(2025, 12, 8),  'time': '8:15 pm', 'away': 'Philadelphia Eagles',  'home': 'Los Angeles Chargers', 'note': ''},

        # Week 15
        {'week': 15,'date': _dt.date(2025, 12, 11), 'time': '8:15 pm', 'away': 'Atlanta Falcons',      'home': 'Tampa Bay Buccaneers', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'Houston Texans', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Baltimore Ravens',     'home': 'Cincinnati Bengals', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Buffalo Bills',        'home': 'New England Patriots', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'Chicago Bears', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Las Vegas Raiders',    'home': 'Philadelphia Eagles', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'New York Jets',        'home': 'Jacksonville Jaguars', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '1:00 pm', 'away': 'Washington Commanders','home': 'New York Giants', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '4:25 pm', 'away': 'Carolina Panthers',    'home': 'New Orleans Saints', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '4:25 pm', 'away': 'Detroit Lions',        'home': 'Los Angeles Rams', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '4:25 pm', 'away': 'Green Bay Packers',    'home': 'Denver Broncos', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '4:25 pm', 'away': 'Indianapolis Colts',   'home': 'Seattle Seahawks', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '4:25 pm', 'away': 'Tennessee Titans',     'home': 'San Francisco 49ers', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 14), 'time': '8:20 pm', 'away': 'Minnesota Vikings',    'home': 'Dallas Cowboys', 'note': ''},
        {'week': 15,'date': _dt.date(2025, 12, 15), 'time': '8:15 pm', 'away': 'Miami Dolphins',       'home': 'Pittsburgh Steelers', 'note': ''},

        # Week 16
        {'week': 16,'date': _dt.date(2025, 12, 18), 'time': '8:15 pm', 'away': 'Los Angeles Rams',     'home': 'Seattle Seahawks', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 20), 'time': '1:00 pm', 'away': 'Green Bay Packers',    'home': 'Chicago Bears', 'note': 'Flex'},
        {'week': 16,'date': _dt.date(2025, 12, 20), 'time': '1:00 pm', 'away': 'Philadelphia Eagles',  'home': 'Washington Commanders', 'note': 'Flex'},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'Buffalo Bills',        'home': 'Cleveland Browns', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'Kansas City Chiefs',   'home': 'Tennessee Titans', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'Dallas Cowboys', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'Minnesota Vikings',    'home': 'New York Giants', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'Baltimore Ravens', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'New York Jets',        'home': 'New Orleans Saints', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '1:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Carolina Panthers', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '4:05 pm', 'away': 'Atlanta Falcons',      'home': 'Arizona Cardinals', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '4:05 pm', 'away': 'Jacksonville Jaguars', 'home': 'Denver Broncos', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '4:25 pm', 'away': 'Las Vegas Raiders',    'home': 'Houston Texans', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 21), 'time': '4:25 pm', 'away': 'Pittsburgh Steelers',  'home': 'Detroit Lions', 'note': ''},
        {'week': 16,'date': _dt.date(2025,  12, 21), 'time': '8:20 pm', 'away': 'Cincinnati Bengals',   'home': 'Miami Dolphins', 'note': ''},
        {'week': 16,'date': _dt.date(2025, 12, 22), 'time': '8:15 pm', 'away': 'San Francisco 49ers',  'home': 'Indianapolis Colts', 'note': ''},

        # Week 17
        {'week': 17,'date': _dt.date(2025, 12, 25), 'time': '1:00 pm', 'away': 'Dallas Cowboys',       'home': 'Washington Commanders', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 25), 'time': '4:30 pm', 'away': 'Detroit Lions',        'home': 'Minnesota Vikings', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 25), 'time': '8:15 pm', 'away': 'Denver Broncos',       'home': 'Kansas City Chiefs', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 27), 'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'Cincinnati Bengals', 'note': 'Flex'},
        {'week': 17,'date': _dt.date(2025, 12, 27), 'time': '1:00 pm', 'away': 'Baltimore Ravens',     'home': 'Green Bay Packers', 'note': 'Flex'},
        {'week': 17,'date': _dt.date(2025, 12, 27), 'time': '1:00 pm', 'away': 'Houston Texans',       'home': 'Los Angeles Chargers', 'note': 'Flex'},
        {'week': 17,'date': _dt.date(2025, 12, 27), 'time': '1:00 pm', 'away': 'New York Giants',      'home': 'Las Vegas Raiders', 'note': 'Flex'},
        {'week': 17,'date': _dt.date(2025, 12, 27), 'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'Carolina Panthers', 'note': 'Flex'},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '1:00 pm', 'away': 'Jacksonville Jaguars', 'home': 'Indianapolis Colts', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '1:00 pm', 'away': 'New England Patriots', 'home': 'New York Jets', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Tennessee Titans', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '1:00 pm', 'away': 'Pittsburgh Steelers',  'home': 'Cleveland Browns', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '1:00 pm', 'away': 'Tampa Bay Buccaneers', 'home': 'Miami Dolphins', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '4:25 pm', 'away': 'Philadelphia Eagles',  'home': 'Buffalo Bills', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 28), 'time': '8:20 pm', 'away': 'Chicago Bears',        'home': 'San Francisco 49ers', 'note': ''},
        {'week': 17,'date': _dt.date(2025, 12, 29), 'time': '8:15 pm', 'away': 'Los Angeles Rams',     'home': 'Atlanta Falcons', 'note': ''},

        # Week 18
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Arizona Cardinals',    'home': 'Los Angeles Rams', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Baltimore Ravens',     'home': 'Pittsburgh Steelers', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Carolina Panthers',    'home': 'Tampa Bay Buccaneers', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Cleveland Browns',     'home': 'Cincinnati Bengals', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Dallas Cowboys',       'home': 'New York Giants', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Detroit Lions',        'home': 'Chicago Bears', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Green Bay Packers',    'home': 'Minnesota Vikings', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Indianapolis Colts',   'home': 'Houston Texans', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Kansas City Chiefs',   'home': 'Las Vegas Raiders', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Los Angeles Chargers', 'home': 'Denver Broncos', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Miami Dolphins',       'home': 'New England Patriots', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'New Orleans Saints',   'home': 'Atlanta Falcons', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'New York Jets',        'home': 'Buffalo Bills', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Seattle Seahawks',     'home': 'San Francisco 49ers', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Tennessee Titans',     'home': 'Jacksonville Jaguars', 'note': 'Flex'},
        {'week': 18,'date': _dt.date(2026, 1, 3),  'time': '1:00 pm', 'away': 'Washington Commanders','home': 'Philadelphia Eagles', 'note': 'Flex'},
    ]